### ISSUE TITLE
Design front-end

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-connect/epiverse-search#13]

**Comment by chartgerink** [comment]
I spent too much time thinking about the design structure, and in order to get myself off my ass I started a mock up. After discussing with @Bisaloo, search + map will be part of one micro-site.

You can view a very simple mock up, with interactivity on Penpot: https://design.penpot.app/#/view/f5fe9278-89db-81e9-8004-f9e8503e465d?page-id=f5fe9278-89db-81e9-8004-f9e8503e465e&section=interactions&index=0&share-id=1ab1fa36-da8e-809d-8004-f9f5c9a272e3

The grey square boxes underneath the "search bar" are placeholders for the WHO and data.org logo's. Here is also a recording, to make sure you see all the functionality I want you to see and provide your thoughts on:

https://github.com/user-attachments/assets/1ae69a89-cd73-427f-bf85-92c9f219ab94

What are your initial thoughts about the structure? I am sharing for early feedback and will also be able to demonstrate for our WHO meeting, if desired.

PS: Cross posted to https://github.com/epiverse-connect/epiverse-map/issues/6
